server.port=8443
server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=${KEYSTORE_PASSWORD:keytool}
server.ssl.key-store=classpath:keystore-local.p12
server.ssl.key-alias=tomcat
server.address=0.0.0.0

frame.processor.url=http://frame-processor:5000